# Generated by Django 5.2.8 on 2025-11-28 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_booking_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_global_slot_per_day',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('date', 'time_slot')},
        ),
    ]
