# Generated by Django 5.2.8 on 2025-11-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_amount_paid_booking_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_type',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='full', max_length=20),
        ),
    ]
