# Generated by Django 5.2.8 on 2025-11-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_total_payable_alter_booking_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='evening_pricing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
