# Generated by Django 5.2.8 on 2025-11-29 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_alter_user_phone_number'),
        ('bookings', '0011_booking_total_payable_alter_booking_payment_type'),
    ]

    operations = [
    ]
