# Generated by Django 5.2.8 on 2025-12-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_service_evening_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
