# Generated by Django 5.2.8 on 2025-12-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_merge_20251129_1651'),
        ('bookings', '0012_service_evening_pricing'),
    ]

    operations = [
    ]
