# Generated by Django 5.2.8 on 2025-12-03 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_booking_expires_at'),
        ('bookings', '0013_merge_20251201_0849'),
    ]

    operations = [
    ]
