from django.urls import path
from .views import (request_otp,
                    verify_otp,
                    TimeSlotListView,
                    BookingCreateView,
                    CreateRazorpayOrderView,
                    VerifyPaymentView,
                    RazorpayWebhookView,
                    get_services,
                    SetNameAndEmailView,
                    BookingDetailView,
                    MyBookingsView,
                    health_check,
                    admin_bookings_dashboard,
                    admin_check_slots,
                    admin_booking_create,
                    admin_booking_cancel,
                    admin_booking_delete,
                    )

urlpatterns = [
    path('auth/request-otp/', request_otp, name='request_otp'),
    path('auth/verify-otp/', verify_otp, name='verify_otp'),
    path('slots/', TimeSlotListView.as_view(), name='time-slot-list'),
    path('bookings/', BookingCreateView.as_view(), name='booking-create'),
    path('create-order/', CreateRazorpayOrderView.as_view(), name='create_razorpay_order'),
    path('verify-payment/', VerifyPaymentView.as_view(), name='verify_payment'),
    path('webhook/', RazorpayWebhookView.as_view(), name='razorpay_webhook'),
    path('services/', get_services, name='get_services'),
    path('set-name-email/', SetNameAndEmailView.as_view(), name='set_name_email'),
    path('my-bookings/', MyBookingsView.as_view() ),
    path('bookings/<uuid:booking_id>/', BookingDetailView.as_view(), name='booking-detail'),
    path('health-check/', health_check, name='health_check'),
    
    # Custom Green Admin Dashboard
    path('admin-dashboard/', admin_bookings_dashboard, name='admin_bookings_dashboard'),
    path('admin-dashboard/check-slots/', admin_check_slots, name='admin_check_slots'),
    path('admin-dashboard/booking/create/', admin_booking_create, name='admin_booking_create'),
    path('admin-dashboard/booking/cancel/<uuid:booking_id>/', admin_booking_cancel, name='admin_booking_cancel'),
    path('admin-dashboard/booking/delete/<uuid:booking_id>/', admin_booking_delete, name='admin_booking_delete'),
]
