# Generated by Django 5.2.8 on 2025-11-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_duration_hours'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('date', 'time_slot')},
        ),
    ]
